### ISSUE TITLE
can't start observer client on bd5acc9a22b4198d8f305d666417d825675f8b95

### ISSUE THREAD

**Issue by alokmenghrajani** [vita-epfl/I_like_trains#105]
When trying to start observer client on bd5acc9a22b4198d8f305d666417d825675f8b95
```
(.venv) coder@Guestys-Air I_like_trains % python -m client 
pygame 2.6.1 (SDL 2.28.4, Python 3.12.9)
Hello from the pygame community. https://www.pygame.org/contribute.html
2025-04-09 17:40:07.349 Python[92659:5161995] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
2025-04-09 17:40:07,661 - client - INFO - Starting client loop
2025-04-09 17:40:07,662 - client.network - INFO - Successfully connected to server at localhost:5555 from local 0.0.0.0:63655
2025-04-09 17:40:07,767 - client - INFO - Connected to server successfully
2025-04-09 17:40:07,836 - client - DEBUG - Sending agent ids: , , observer
2025-04-09 17:40:07,837 - client - INFO - Running client loop: True
2025-04-09 17:40:07,838 - client.network - DEBUG - Received join success response
2025-04-09 17:40:08,017 - client - INFO - Received initial state from server
2025-04-09 17:40:08,018 - client - INFO - Game lifetime set to 60 seconds
2025-04-09 17:40:08,018 - client.network - INFO - Game has started
2025-04-09 17:40:08,195 - client.game_state - INFO - Updated game dimensions: game width = 460, screen width = 790.0
2025-04-09 17:40:08,195 - client.game_state - INFO - Cell size updated: 20
2025-04-09 17:40:08,231 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'
2025-04-09 17:40:08,236 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'
2025-04-09 17:40:08,255 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'
2025-04-09 17:40:08,271 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'
2025-04-09 17:40:08,288 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'
2025-04-09 17:40:08,305 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'
2025-04-09 17:40:08,322 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'
2025-04-09 17:40:08,339 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'
2025-04-09 17:40:08,356 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'
2025-04-09 17:40:08,373 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'
2025-04-09 17:40:08,390 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'
2025-04-09 17:40:08,407 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'
2025-04-09 17:40:08,424 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'
2025-04-09 17:40:08,441 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'
2025-04-09 17:40:08,458 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'
2025-04-09 17:40:08,475 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'
2025-04-09 17:40:08,492 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'
2025-04-09 17:40:08,509 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'
2025-04-09 17:40:08,526 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'
2025-04-09 17:40:08,543 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'
2025-04-09 17:40:08,560 - client.renderer - ERROR - Error drawing trains: 'Client' object has no attribute 'nickname'

```

**Comment by alokmenghrajani** [comment]
`git bisect` seems to indicate that the regression appeared in 3d8cfafca63f361de897b0f37de10465b97ccc97?
